cabal-version:      3.0
name:                arenaos
version:             0.1.0.0
build-type:          Simple

library
    exposed-modules:  Shell.Persistence.SQLite.Error
                      Shell.Persistence.SQLite.Connection
                      Shell.Persistence.SQLite.Schema
                      Shell.Persistence.SQLite.ParticipantRepository
                      Shell.Persistence.Port
                      Domain.Participant
                      Domain.Tournament
                      Shell.Persistence.SQLite.TournamentRepository
                      Domain.Registration
                      Shell.Persistence.SQLite.RegistrationRepository
                      Shell.Persistence.SQLite.BracketRepository
                      Shell.Persistence.SQLite.Common
                      Domain.Bracket
                      Domain.Match
                      Shell.Persistence.SQLite.MatchRepository
                      Engine.Error
                      Engine.Validation
                      Engine.BracketGeneration
                      Engine.Seeding
                      Engine.ByeResolution
                      Engine.Advancement
                      Engine.Materialization
                      Application.UseCases.CreateTournament
                      Application.UseCases.RegisterParticipant
                      Application.UseCases.StartMatch
                      Domain.MatchError
                      Application.UseCases.CompleteTournament
                      Domain.TournamentError
                      Application.UseCases.RecordMatchResult
                      Application.UseCases.GenerateBracket
                      Domain.Ids
                      Application.Internal.MatchCreation
                      Domain.User
                      Engine.User
                      Shell.Persistence.SQLite.UserRepository
                      Application.UseCases.RegisterUser
                      Application.UseCases.LoginUser
                      Application.Internal.Authorization
                      Shell.Auth.Session
                      Application.UseCases.LogoutUser
                      Shell.Infrastructure.PasswordHasher
                      Application.UseCases.ChangePassword
                      Application.UseCases.UpdateProfile
                      Application.UseCases.SetAccountStatus
                      Application.Internal.LifecycleTransition
                      Application.UseCases.PublishTournament
                      Application.UseCases.OpenRegistration
                      Application.UseCases.CloseRegistration    
                      Application.UseCases.StartTournament
                      Application.UseCases.CancelTournament
                      Application.UseCases.UpdateTournamentName
                      Application.UseCases.UpdateTournamentMaxParticipants
                      Application.UseCases.UpdateTournamentVisibility
                      Application.UseCases.UpdateTournamentFormat
                      Application.UseCases.GetOrganizerDashboard
                      Domain.TournamentHistory
                      Shell.Persistence.SQLite.TournamentHistoryRepository
                      Application.UseCases.GetTournamentHistory

    hs-source-dirs:   .
    build-depends:    base
                    , sqlite-simple
                    , mtl
                    , text
                    , containers
                    , argon2
                    , entropy
                    , directory
                    , filepath
                    , text-short
    default-language: Haskell2010

executable arenaos
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    base
                    , arenaos
                    , mtl
                    , text
    default-language: Haskell2010

test-suite arenaos-test
    type:             exitcode-stdio-1.0
    main-is:          Spec.hs
    hs-source-dirs:   test
    build-depends:    base
                    , arenaos
                    , hspec
                    , sqlite-simple
                    , directory
                    , mtl
                    , text
    default-language: Haskell2010