-- Shell.Persistence.Port
-- Repository ports (Architecture.md Section 13.4). These describe
-- what persistence must provide; they say nothing about how. No
-- adapter-specific imports belong here -- only Domain types and the
-- shared PersistenceError type.
--
-- Save/delete semantics: RC-01 (save is upsert), RC-02 (delete is
-- not idempotent -- deleting a missing object is NotFound).
-- Execution and failure model: ADR-007. Repository methods return
-- domain values directly; failures propagate as exceptions and are
-- translated to Either PersistenceError once, by the adapter runner
-- (e.g. runSQLiteM), not by these methods themselves.
-- NewTournament lives here rather than in Domain because it fails
-- the Two-Architectures Test: under a domain-generated-identity
-- backend (UUIDs), it wouldn't need to exist at all. It expresses a
-- persistence construction constraint, not a business concept.

module Shell.Persistence.Port
  ( ParticipantRepository(..)
  , TournamentRepository(..)
  , NewTournament(..)
  , RegistrationRepository(..)
  , Registration(..)
  , NewRegistration(..)
  , BracketRepository(..)
  , MatchRepository(..)
  , NewMatch(..)
  ,RegistrationId(..)
  ,ParticipantId(..)
  ,UserId(..)
  ,Transactional(..)
  ,UserRepository(..)
  ,PasswordHasher(..)
  ,NewUser(..)
  ,TournamentHistoryRepository(..)
  ,RoleRepository(..)
  ,AuditLogRepository(..)
  ,EFootballScoreRepository(..)
  
  ) where

import Domain.Participant (Player, PlayerName, Team, TeamName, Participant, ParticipantId)
import Domain.Tournament (Tournament, TournamentId, TournamentName, OrganizerName, TournamentFormat, Visibility, TournamentState)
import Domain.Registration (Registration, RegistrationId)
import Domain.Bracket (Bracket, BracketId, BracketNode, BracketNodeId)
import Domain.Match (Match, MatchId)
import Domain.User (User(..), Username(..), Email(..), PasswordHash(..), AccountStatus(..))
import Domain.Ids ( UserId(..))
import Domain.TournamentHistory (TournamentHistoryEvent, TournamentHistoryEntry)
import Domain.Role (Role(..))
import Domain.Audit (AuditEvent(..))
import Domain.Scoreable (EFootballScore)
import Data.Map.Strict (Map)
import Data.Text (Text)
-- Owns Participant identity (ADR-006) and its constituents (Player, Team).
-- resolveParticipant is the one operation every other repository depends
-- on indirectly -- it belongs here, per DP-002, not duplicated at each
-- call site.
class Monad m => ParticipantRepository m where
    savePlayer   :: Player -> m ()
    getPlayer    :: PlayerName -> m Player
    deletePlayer :: PlayerName -> m ()

    saveTeam     :: Team -> m ()
    getTeam      :: TeamName -> m Team
    deleteTeam   :: TeamName -> m ()
    teamExists   :: TeamName -> m Bool

    resolveParticipant :: Participant -> m ParticipantId
    getParticipant     :: ParticipantId -> m Participant

-- Creation-shaped input for TournamentRepository.createTournament.
-- Not a Domain Model type (see Document 3's own scope note) -- it
-- exists only because TournamentId is persistence-generated
-- (INTEGER PRIMARY KEY), so a pre-persistence Tournament value can
-- never honestly be constructed. Omits exactly the fields the
-- system determines, not the caller:
--   TournamentId    -- generated by persistence
--   TournamentState -- always Draft per FR-TM-001
--   TournamentBracket -- always Nothing at creation
-- Everything else (name, organizer, format, visibility, max
-- participants) is genuine caller input per FR-TM-001/002 -- see
-- the Tournament type itself, which has none of these as Maybe.
data NewTournament = NewTournament
    { newTournamentName            :: TournamentName
    , newTournamentOrganizer       :: OrganizerName
    , newTournamentFormat          :: TournamentFormat
    , newTournamentVisibility      :: Visibility
    , newTournamentMaxParticipants :: Int
    , newTournamentOwner :: UserId
    }

-- createTournament is NOT covered by RC-01 -- it has no natural key
-- to upsert against, so it is not idempotent: each call mints a
-- fresh TournamentId. saveTournament remains the RC-01-compliant
-- upsert path for all post-creation updates, including attaching a
-- Bracket once one is generated (tournament w/ NULL bracket_id ->
-- bracket -> saveTournament with tournamentBracket = Just newId,
-- per the schema's circular-FK insert order).
class Monad m => TournamentRepository m where
    createTournament :: NewTournament -> m TournamentId
    saveTournament   :: Tournament -> m ()
    getTournament    :: TournamentId -> m Tournament
    deleteTournament :: TournamentId -> m ()
    listTournamentsByOwner :: UserId -> m [Tournament]
    updateTournamentState    :: TournamentId -> TournamentState -> m ()
    updateTournamentName     :: TournamentId -> TournamentName -> m ()
    updateTournamentMaxParticipants :: TournamentId -> Int -> m ()
    updateTournamentVisibility :: TournamentId -> Visibility -> m ()
    updateTournamentFormat   :: TournamentId -> TournamentFormat -> m ()
    listAllTournaments :: m [Tournament]

-- Creation-shaped input for RegistrationRepository.createRegistration.
-- No status field -- RegistrationStatus has exactly one constructor
-- in v0.1 (INV-2, FR-TM-009); the repository hardcodes Confirmed at
-- insert, same pattern as createTournament hardcoding Draft.
-- Takes ParticipantId, not Participant -- identity resolution stays
-- exclusively in ParticipantRepository per DP-002; this repository
-- never calls resolveParticipant.
data NewRegistration = NewRegistration
    { newRegistrationTournament  :: TournamentId
    , newRegistrationParticipant :: ParticipantId
    }

-- No saveRegistration -- for v0.1, Registration has no legitimate
-- update surface: registrationTournament/registrationParticipant
-- are immutable once created (DI-10), and registrationStatus has
-- only one inhabitant. A future updateRegistrationStatus would be
-- the correct shape if INV-2 is ever exercised, not a blanket save.
class Monad m => RegistrationRepository m where
    createRegistration :: NewRegistration -> m RegistrationId
    getRegistration    :: RegistrationId -> m Registration
    deleteRegistration :: RegistrationId -> m ()
    listRegistrations  :: TournamentId -> m [Registration]


class Monad m => BracketRepository m where
    createBracket :: TournamentId -> m BracketId
    saveBracket :: Bracket -> [BracketNode] -> m (Map BracketNodeId BracketNodeId)
    getBracket    :: BracketId -> m (Bracket, [BracketNode])
    updateNodeSlots :: BracketNode -> m ()
    deleteBracket :: BracketId -> m ()

data NewMatch = NewMatch
    { newMatchTournament  :: TournamentId
    , newMatchBracket     :: BracketId
    , newMatchBracketNode :: BracketNodeId
    , newMatchCompetitorA :: ParticipantId
    , newMatchCompetitorB :: ParticipantId
    }
    deriving (Eq, Show)


class Monad m => MatchRepository m where
    createMatch           :: NewMatch -> m MatchId
    saveMatch             :: Match -> m ()
    getMatch              :: MatchId -> m Match
    listMatchesForBracket :: BracketId -> m [Match]
    deleteMatch           :: MatchId -> m ()

class Monad m => Transactional m where
    withTxN :: m a -> m a

data NewUser = NewUser
    { newUserUsername     :: Username
    , newUserEmail        :: Email
    , newUserPasswordHash :: PasswordHash
    }

class Monad m =>  UserRepository m where
  createUser         :: NewUser -> m UserId
  findUserByUsername :: Username -> m (Maybe User)
  findUserByEmail     :: Email -> m (Maybe User)
  findUserById        :: UserId -> m (Maybe User)
  updatePasswordHash     :: UserId -> PasswordHash -> m ()
  updateUsername :: UserId -> Username -> m ()
  updateEmail    :: UserId -> Email -> m ()
  updateAccountStatus :: UserId -> AccountStatus -> m ()

class Monad m => PasswordHasher m where
    hashPassword   :: Text -> m PasswordHash
    verifyPassword :: Text -> PasswordHash -> m Bool

class TournamentHistoryRepository m where
    recordHistoryEvent  :: TournamentId -> TournamentHistoryEvent -> m ()
    getTournamentHistory :: TournamentId -> m [TournamentHistoryEntry]


class Monad m => RoleRepository m where
    insertRoleMembership :: UserId -> Role -> m ()
    deleteRoleMembership :: UserId -> Role -> m ()
    getRoles             :: UserId -> m [Role]
    listRoleHolders      :: Role -> m [UserId]

class Monad m => AuditLogRepository m where
    recordAuditEvent         :: AuditEvent -> m ()
    listAuditEventsForEntity :: UserId -> m [AuditEvent]

class Monad m => EFootballScoreRepository m where
  saveEFootballScore :: MatchId -> EFootballScore -> EFootballScore -> m ()
  getEFootballScore   :: MatchId -> m (Maybe (EFootballScore, EFootballScore))

